openapi: "3.0.2"

info: 
  title: Game API
  version: 1.0.0
servers:
  - url: https://us-central1-back-to-life-again.cloudfunctions.net/app
  
paths:
  /games:
    get:
      operationId: getGames
      responses:
        '200':
          description: Successful fetching of games
      x-openai-isConsequential: false
  /games/{game}:
    post:
      operationId: createGame
      x-openai-isConsequential: false
      parameters:
        - in: path
          name: game
          required: true
          schema:
            type: string
  /games/{gameId}/players/{player}:
    post:
      operationId: joinGame
      x-openai-isConsequential: false
      parameters:
        - in: path
          name: gameId
          required: true
          schema:
            type: string
        - in: path
          name: player
          required: true
          schema:
            type: string
  /games/{gameId}/players/{playerId}/unit/{unitId}/heal/{targetId}:
    post:
      operationId: healUnit
      x-openai-isConsequential: false
      parameters:
        - in: path
          name: gameId
          required: true
          schema:
            type: string
        - in: path
          name: playerId
          required: true
          schema:
            type: string
        - in: path
          name: unitId
          required: true
          schema:
            type: string
        - in: path
          name: targetId
          required: true
          schema:
            type: string
  /games/{gameId}/players/{playerId}/unit/{unitId}/attack/{targetId}:
    post:
      operationId: attackUnit
      x-openai-isConsequential: false
      parameters:
        - in: path
          name: gameId
          required: true
          schema:
            type: string
        - in: path
          name: playerId
          required: true
          schema:
            type: string
        - in: path
          name: unitId
          required: true
          schema:
            type: string
        - in: path
          name: targetId
          required: true
          schema:
            type: string
  /games/{gameId}/players/units/{playerId}/units/{unitId}:
    get:
      operationId: getPlayerUnits
      x-openai-isConsequential: false
      parameters:
        - in: path
          name: gameId
          required: true
          schema:
            type: string
        - in: path
          name: playerId
          required: true
          schema:
            type: string
        - in: path
          name: unitId
          required: true
          schema:
            type: string
  /games/{gameId}/players/units:
    get:
      operationId: getAllPlayerUnits
      x-openai-isConsequential: false
      parameters:
        - in: path
          name : gameId
          required: true
          schema:
            type: string
  /games/{gameId}/unit/{unitId}/pickup/{item}:
    post:
      x-openai-isConsequential: false
      operationId: pickupItem
      parameters:
        - in: path
          name: gameId
          required: true
          schema:
            type: string
        - in: path
          name: unitId
          required: true
          schema:
            type: string
        - in: path
          name: item
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Item picked up successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  effect:
                    type: string
                  amount:
                    type: integer
                  newAmount:
                    type: integer
        '400':
          description: An item with that name does not exist or unit does not exist
          content:
            text/plain:
              schema:
                type: string